# Generated by Django 5.1.7 on 2025-03-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redactor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redactor',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redactor',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redactor',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='redactor',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
