# Generated by Django 5.1.7 on 2025-03-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_agency', '0002_redactor_bio_redactor_instagram_redactor_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redactor',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redactor',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='title',
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='redactor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
